import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/app/provider/app-provider";
import { cn } from "@/shared/lib/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased font-sans")}>
        <React.Fragment>
          <AppProvider>{children}</AppProvider>
        </React.Fragment>
      </body>
    </html>
  );
}
